version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "project-db"
      POSTGRES_USER: "user-db"
      POSTGRES_PASSWORD: "password-project-db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"